services:
  # Main Serverpod backend
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freshpickkat_server
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8082:8082"
    command: ["/app/server", "--runmode=production"]
    
    environment:
      - runmode=production
      - serverid=default
      - logging=verbose
      - role=monolith
      - SERVERPOD_PASSWORD_database=${SERVERPOD_PASSWORD_database}
      - SERVERPOD_PASSWORD_redis=${SERVERPOD_PASSWORD_redis}
      - SERVERPOD_API_SERVER_PUBLIC_HOST=${PUBLIC_HOST}
      - SERVERPOD_WEB_SERVER_PUBLIC_HOST=${PUBLIC_HOST}
      - SERVERPOD_INSIGHTS_SERVER_PUBLIC_HOST=${PUBLIC_HOST}
      - SERVERPOD_SERVICE_SECRET=${SERVERPOD_SERVICE_SECRET}
      - SERVERPOD_EMAIL_SECRET_HASH_PEPPER=${SERVERPOD_EMAIL_SECRET_HASH_PEPPER}
      - SERVERPOD_JWT_HMAC_SHA512_PRIVATE_KEY=${SERVERPOD_JWT_HMAC_SHA512_PRIVATE_KEY}
      - SERVERPOD_JWT_REFRESH_TOKEN_HASH_PEPPER=${SERVERPOD_JWT_REFRESH_TOKEN_HASH_PEPPER}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - ./config:/app/config

  # Production database
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "127.0.0.1:8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: freshpickkat
      POSTGRES_PASSWORD: ${SERVERPOD_PASSWORD_database}
    volumes:
      - freshpickkat_data:/var/lib/postgresql/data
      - ./migrations/init_extensions.sql:/docker-entrypoint-initdb.d/init_extensions.sql

  # Production redis
  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "127.0.0.1:8091:6379"
    command: redis-server --requirepass "${SERVERPOD_PASSWORD_redis}"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  freshpickkat_data:
