org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1.2 -Djava.net.preferIPv4Stack=true -Dkotlin.daemon.jvmargs=-Dkotlin.metadata.check=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.build.metadata.version.check=false
