// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPtOOOyV6xlvR5FLYvzLumDGwyDl6NlIk',
    appId: '1:784305413937:web:29ce015bf5932d6079da10',
    messagingSenderId: '784305413937',
    projectId: 'freshpickkart-a6824',
    authDomain: 'freshpickkart-a6824.firebaseapp.com',
    storageBucket: 'freshpickkart-a6824.firebasestorage.app',
    measurementId: 'G-9TMPYELK1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbE8qQGVluyYuKu7omcT3-fl8e6TQNY_c',
    appId: '1:784305413937:android:c185d8300afa7c4379da10',
    messagingSenderId: '784305413937',
    projectId: 'freshpickkart-a6824',
    storageBucket: 'freshpickkart-a6824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBktLdQx7uM7HTOlfor0RilDvJC7qnSNh8',
    appId: '1:784305413937:ios:51005c35aa11a36a79da10',
    messagingSenderId: '784305413937',
    projectId: 'freshpickkart-a6824',
    storageBucket: 'freshpickkart-a6824.firebasestorage.app',
    iosBundleId: 'com.freshpickkart.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBktLdQx7uM7HTOlfor0RilDvJC7qnSNh8',
    appId: '1:784305413937:ios:4fe0b63ef9e2402d79da10',
    messagingSenderId: '784305413937',
    projectId: 'freshpickkart-a6824',
    storageBucket: 'freshpickkart-a6824.firebasestorage.app',
    iosBundleId: 'com.freshpickkat.freshpickkatAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPtOOOyV6xlvR5FLYvzLumDGwyDl6NlIk',
    appId: '1:784305413937:web:29ce015bf5932d6079da10',
    messagingSenderId: '784305413937',
    projectId: 'freshpickkart-a6824',
    authDomain: 'freshpickkart-a6824.firebaseapp.com',
    storageBucket: 'freshpickkart-a6824.firebasestorage.app',
    measurementId: 'G-9TMPYELK1H',
  );
}
